"use client";

import { useEffect, useState } from "react";
import {
  X,
  ChevronRight,
  ChevronLeft,
  Check,
  CreditCard,
  CalendarDays,
  SlidersHorizontal,
} from "lucide-react";
import { formatDate } from "@/lib/format";
import { createStudentPlan } from "@/actions/student";
import { DateInput } from "@/components/ui/date-input";

function addMonths(dateStr, n) {
  const d = new Date(dateStr);
  d.setMonth(d.getMonth() + n);
  return d.toISOString().split("T")[0];
}

function generateStandardRows(config, net) {
  const { count, startDate } = config;
  const n = Number(count);
  if (!n || !startDate) return [];

  const perInstallment = Math.floor(net / n);
  const lastExtra = net - perInstallment * n;

  return Array.from({ length: n }, (_, i) => ({
    id: `inst_${i + 1}`,
    date: addMonths(startDate, i + 1),
    amount: i === n - 1 ? perInstallment + lastExtra : perInstallment,
    label: `Installment ${i + 1}`,
  }));
}

const PLAN_TYPES = [
  {
    id: "full_pay",
    icon: <CreditCard className="w-5 h-5" />,
    label: "Full Payment",
    desc: "Single payment on one due date",
  },
  {
    id: "standard_emi",
    icon: <CalendarDays className="w-5 h-5" />,
    label: "Standard EMI",
    desc: "Fixed installments auto-generated by schedule",
  },
  {
    id: "flexible",
    icon: <SlidersHorizontal className="w-5 h-5" />,
    label: "Flexible Plan",
    desc: "Add first installment now, more can be added later",
  },
];

function StepPlanType({ planType, setPlanType, onNext }) {
  return (
    <div className="space-y-3">
      {PLAN_TYPES.map((pt) => (
        <button
          key={pt.id}
          onClick={() => setPlanType(pt.id)}
          className={`w-full text-left flex items-start gap-4 p-4 rounded-xl border transition-colors ${
            planType === pt.id
              ? "border-primary bg-primary/5"
              : "border-border hover:bg-muted/40"
          }`}
        >
          <span
            className={
              planType === pt.id ? "text-primary" : "text-muted-foreground"
            }
          >
            {pt.icon}
          </span>
          <div>
            <p
              className={`text-sm font-semibold ${planType === pt.id ? "text-primary" : "text-foreground"}`}
            >
              {pt.label}
            </p>
            <p className="text-xs text-muted-foreground mt-0.5">{pt.desc}</p>
          </div>
          {planType === pt.id && (
            <Check className="w-4 h-4 text-primary ml-auto shrink-0 mt-0.5" />
          )}
        </button>
      ))}

      <button
        onClick={onNext}
        disabled={!planType}
        className="w-full flex items-center justify-center gap-2 py-3 bg-primary text-primary-foreground font-semibold rounded-lg hover:opacity-90 disabled:opacity-50 mt-2"
      >
        Next <ChevronRight className="w-4 h-4" />
      </button>
    </div>
  );
}

function StepFullPay({ fullPayDate, setFullPayDate, net, onNext, onBack }) {
  return (
    <div className="space-y-5">
      <div className="rounded-lg bg-muted/50 border border-border px-4 py-3 flex items-center justify-between">
        <span className="text-xs font-semibold text-muted-foreground uppercase">
          Amount Due
        </span>
        <span className="text-lg font-bold text-foreground">
          ₹{net.toLocaleString()}
        </span>
      </div>

      <div>
        <label className="block text-xs font-semibold text-muted-foreground mb-1.5">
          Due Date
        </label>
        <DateInput
          required
          value={fullPayDate}
          onChange={(iso) => setFullPayDate(iso)}
        />
      </div>

      <div className="flex gap-3">
        <button
          onClick={onBack}
          className="flex-1 flex items-center justify-center gap-2 py-3 border border-border rounded-lg font-semibold text-sm hover:bg-muted"
        >
          <ChevronLeft className="w-4 h-4" /> Back
        </button>
        <button
          onClick={onNext}
          disabled={!fullPayDate}
          className="flex-1 flex items-center justify-center gap-2 py-3 bg-primary text-primary-foreground font-semibold rounded-lg hover:opacity-90 disabled:opacity-50"
        >
          Preview <ChevronRight className="w-4 h-4" />
        </button>
      </div>
    </div>
  );
}

function StepStandardEMI({ config, setConfig, net, onNext, onBack }) {
  const rows = generateStandardRows(config, net);
  const sum = rows.reduce((a, r) => a + r.amount, 0);
  const valid = rows.length > 0 && sum === net;

  return (
    <div className="space-y-5">
      <div className="grid grid-cols-2 gap-4">
        <div>
          <label className="block text-xs font-semibold text-muted-foreground mb-1.5">
            No. of Installments
          </label>
          <input
            type="number"
            min="1"
            max="36"
            className="input"
            placeholder="e.g. 6"
            value={config.count}
            onChange={(e) => setConfig({ ...config, count: e.target.value })}
          />
        </div>
        <div>
          <label className="block text-xs font-semibold text-muted-foreground mb-1.5">
            Frequency
          </label>
          <select className="input" value={config.frequency} disabled>
            <option value="monthly">Monthly</option>
          </select>
        </div>
      </div>

      <div>
        <label className="block text-xs font-semibold text-muted-foreground mb-1.5">
          Start Date
        </label>
        <DateInput
          value={config.startDate}
          onChange={(iso) => setConfig({ ...config, startDate: iso })}
        />
      </div>

      {/* Preview */}
      {rows.length > 0 && (
        <div className="rounded-lg border border-border overflow-hidden">
          <div className="px-4 py-2.5 bg-muted/40 border-b border-border">
            <p className="text-xs font-semibold text-muted-foreground uppercase">
              Preview
            </p>
          </div>
          <table className="w-full text-sm">
            <thead className="text-xs text-muted-foreground">
              <tr>
                <th className="px-4 py-2 text-left">Label</th>
                <th className="px-4 py-2 text-left">Date</th>
                <th className="px-4 py-2 text-right">Amount</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-border">
              {rows.map((r) => (
                <tr key={r.id}>
                  <td className="px-4 py-2.5 text-muted-foreground">
                    {r.label}
                  </td>
                  <td className="px-4 py-2.5">{formatDate(r.date)}</td>
                  <td className="px-4 py-2.5 text-right font-semibold">
                    ₹{r.amount.toLocaleString()}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      <div className="flex gap-3">
        <button
          onClick={onBack}
          className="flex-1 flex items-center justify-center gap-2 py-3 border border-border rounded-lg font-semibold text-sm hover:bg-muted"
        >
          <ChevronLeft className="w-4 h-4" /> Back
        </button>
        <button
          onClick={onNext}
          disabled={!valid}
          className="flex-1 flex items-center justify-center gap-2 py-3 bg-primary text-primary-foreground font-semibold rounded-lg hover:opacity-90 disabled:opacity-50"
        >
          Preview <ChevronRight className="w-4 h-4" />
        </button>
      </div>
    </div>
  );
}

function StepFlexible({
  firstInstallment,
  setFirstInstallment,
  net,
  onNext,
  onBack,
}) {
  const amount = Number(firstInstallment.amount) || 0;
  const remaining = net - amount;
  const isValid = firstInstallment.date && amount > 0 && amount <= net;

  return (
    <div className="space-y-5">
      <div className="rounded-lg bg-muted/50 border border-border px-4 py-3 flex items-center justify-between">
        <span className="text-xs font-semibold text-muted-foreground uppercase">
          Total Net Payable
        </span>
        <span className="text-lg font-bold text-foreground">
          ₹{net.toLocaleString()}
        </span>
      </div>

      <div>
        <label className="block text-xs font-semibold text-muted-foreground mb-1.5">
          First Installment Due Date
        </label>
        <DateInput
          value={firstInstallment.date}
          onChange={(iso) =>
            setFirstInstallment((prev) => ({ ...prev, date: iso }))
          }
        />
      </div>

      <div>
        <label className="block text-xs font-semibold text-muted-foreground mb-1.5">
          First Installment Amount (₹)
        </label>
        <input
          type="number"
          min="1"
          max={net}
          className="input font-semibold"
          placeholder="e.g. 10000"
          value={firstInstallment.amount}
          onChange={(e) =>
            setFirstInstallment((prev) => ({ ...prev, amount: e.target.value }))
          }
        />
      </div>

      {amount > 0 && (
        <div
          className={`rounded-lg px-4 py-3 flex items-center justify-between border ${
            remaining === 0
              ? "bg-primary/5 border-primary/20"
              : "bg-muted/50 border-border"
          }`}
        >
          <span className="text-xs font-semibold text-muted-foreground uppercase">
            Balance after this installment
          </span>
          <span
            className={`text-base font-bold ${remaining === 0 ? "text-primary" : "text-foreground"}`}
          >
            ₹{remaining.toLocaleString()}
          </span>
        </div>
      )}

      {amount > net && (
        <p className="text-xs text-destructive">
          Amount cannot exceed net payable
        </p>
      )}

      <p className="text-xs text-muted-foreground">
        Remaining balance can be collected via additional installments after
        plan is assigned.
      </p>

      <div className="flex gap-3">
        <button
          onClick={onBack}
          className="flex-1 flex items-center justify-center gap-2 py-3 border border-border rounded-lg font-semibold text-sm hover:bg-muted"
        >
          <ChevronLeft className="w-4 h-4" /> Back
        </button>
        <button
          onClick={onNext}
          disabled={!isValid}
          className="flex-1 flex items-center justify-center gap-2 py-3 bg-primary text-primary-foreground font-semibold rounded-lg hover:opacity-90 disabled:opacity-50"
        >
          Preview <ChevronRight className="w-4 h-4" />
        </button>
      </div>
    </div>
  );
}

function StepReview({
  net,
  planType,
  installmentRows,
  onBack,
  onConfirm,
  isSubmitting,
}) {
  const planLabel = {
    full_pay: "Full Payment",
    standard_emi: "Standard EMI",
    flexible: "Flexible Plan",
  }[planType];

  return (
    <div className="space-y-5">
      {/* Summary */}
      <div className="rounded-xl border border-border overflow-hidden">
        <div className="px-4 py-3 bg-muted/40 border-b border-border flex items-center justify-between">
          <p className="text-xs font-semibold text-muted-foreground uppercase">
            Plan Summary
          </p>
          <span className="text-xs font-semibold px-2.5 py-1 rounded bg-primary/10 text-primary border border-primary/20">
            {planLabel}
          </span>
        </div>
        <div className="grid grid-cols-2 divide-x divide-border text-sm">
          <div className="px-4 py-3">
            <p className="text-xs text-muted-foreground mb-1">Course Fee</p>
            <p className="font-bold text-primary">₹{net.toLocaleString()}</p>
          </div>
          <div className="px-4 py-3">
            <p className="text-xs text-muted-foreground mb-1">Installments</p>
            <p className="font-semibold">{installmentRows.length}</p>
          </div>
        </div>
      </div>

      {/* Installments preview */}
      <div className="rounded-xl border border-border overflow-hidden">
        <div className="px-4 py-2.5 bg-muted/40 border-b border-border">
          <p className="text-xs font-semibold text-muted-foreground uppercase">
            Installments ({installmentRows.length})
          </p>
        </div>
        <div className="max-h-52 overflow-y-auto">
          <table className="w-full text-sm">
            <thead className="text-xs text-muted-foreground bg-muted/20 sticky top-0">
              <tr>
                <th className="px-4 py-2 text-left">Label</th>
                <th className="px-4 py-2 text-left">Due Date</th>
                <th className="px-4 py-2 text-right">Amount</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-border">
              {installmentRows.map((r) => (
                <tr key={r.id}>
                  <td className="px-4 py-2.5 text-muted-foreground">
                    {r.label || `Installment`}
                  </td>
                  <td className="px-4 py-2.5">{formatDate(r.date)}</td>
                  <td className="px-4 py-2.5 text-right font-semibold">
                    ₹{Number(r.amount).toLocaleString()}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      <div className="flex gap-3">
        <button
          onClick={onBack}
          disabled={isSubmitting}
          className="flex-1 flex items-center justify-center gap-2 py-3 border border-border rounded-lg font-semibold text-sm hover:bg-muted disabled:opacity-50"
        >
          <ChevronLeft className="w-4 h-4" /> Edit
        </button>
        <button
          onClick={onConfirm}
          disabled={isSubmitting}
          className="flex-1 flex items-center justify-center gap-2 py-3 bg-primary text-primary-foreground font-semibold rounded-lg hover:opacity-90 disabled:opacity-50"
        >
          {isSubmitting ? (
            "Saving..."
          ) : (
            <>
              <Check className="w-4 h-4" /> Confirm Plan
            </>
          )}
        </button>
      </div>
    </div>
  );
}

const STEP_LABELS = ["Plan Type", "Configure", "Review"];

export function AssignPlanWizard({
  open,
  onClose,
  student,
  studentId,
  onPlanCreated,
}) {
  const [step, setStep] = useState(1);
  const [isSubmitting, setIsSubmitting] = useState(false);

  const [planType, setPlanType] = useState("");
  const [standardConfig, setStandardConfig] = useState({
    count: "",
    frequency: "monthly",
    startDate: "",
  });
  const [firstInstallment, setFirstInstallment] = useState({
    date: "",
    amount: "",
  });
  const [fullPayDate, setFullPayDate] = useState("");

  const net = student?.finalFee || 0;

  // Escape key
  useEffect(() => {
    if (!open) return;
    const onKey = (e) => {
      if (e.key === "Escape") onClose();
    };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [open, onClose]);

  if (!open) return null;

  // Build final installment rows for review + confirm
  const buildInstallmentRows = () => {
    if (planType === "full_pay") {
      return [
        { id: "fp_1", date: fullPayDate, amount: net, label: "Full Payment" },
      ];
    }
    if (planType === "standard_emi") {
      return generateStandardRows(standardConfig, net);
    }
    if (planType === "flexible") {
      return [
        {
          id: "flex_1",
          date: firstInstallment.date,
          amount: Number(firstInstallment.amount),
          label: "Installment 1",
        },
      ];
    }
    return [];
  };

  const handleConfirm = async () => {
    setIsSubmitting(true);
    const rows = buildInstallmentRows();

    try {
      const typeMap = {
        full_pay: "full",
        standard_emi: "emi",
        flexible: "flexible",
      };
      const type = typeMap[planType];

      const payload = { type, totalAmount: net };

      if (type === "emi") {
        payload.installments = rows.map((r) => ({ dueDate: r.date }));
      } else if (type === "flexible") {
        payload.installments = rows.map((r) => ({
          amount: Number(r.amount),
          dueDate: r.date,
        }));
      }

      const result = await createStudentPlan(studentId, payload);

      onPlanCreated();
      onClose();
    } catch (err) {
      const { toast } = await import("sonner");
      toast.error(err.message || "Failed to assign plan");
    } finally {
      setIsSubmitting(false);
    }
  };

  const stepTitle = STEP_LABELS[step - 1];

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center p-4"
      onClick={(e) => {
        if (e.target === e.currentTarget) onClose();
      }}
    >
      <div className="absolute inset-0 bg-foreground/20 backdrop-blur-sm" />

      <div className="relative w-full max-w-lg card flex flex-col max-h-[90vh]">
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-border shrink-0">
          <div>
            <h2 className="text-sm font-bold text-foreground">
              Assign Fee Plan
            </h2>
            <p className="text-xs text-muted-foreground mt-0.5">
              Step {step} of 3 — {stepTitle}
            </p>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 rounded-lg hover:bg-muted text-muted-foreground"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Progress bar */}
        <div className="h-1 bg-muted shrink-0">
          <div
            className="h-full bg-primary transition-all duration-300"
            style={{ width: `${(step / 3) * 100}%` }}
          />
        </div>

        {/* Step indicators */}
        <div className="flex px-6 py-3 border-b border-border gap-1 shrink-0">
          {STEP_LABELS.map((label, i) => (
            <div key={label} className="flex items-center gap-1 flex-1">
              <div
                className={`w-5 h-5 rounded-full flex items-center justify-center text-xs font-bold shrink-0 ${
                  i + 1 < step
                    ? "bg-primary text-primary-foreground"
                    : i + 1 === step
                      ? "bg-primary/10 text-primary border border-primary"
                      : "bg-muted text-muted-foreground"
                }`}
              >
                {i + 1 < step ? <Check className="w-3 h-3" /> : i + 1}
              </div>
              <span
                className={`text-xs hidden sm:block truncate ${
                  i + 1 === step
                    ? "text-primary font-semibold"
                    : "text-muted-foreground"
                }`}
              >
                {label}
              </span>
              {i < 2 && (
                <div className="h-px flex-1 bg-border mx-1 hidden sm:block" />
              )}
            </div>
          ))}
        </div>

        {/* Enrolled fee banner */}
        <div className="px-6 py-3 bg-muted/40 border-b border-border shrink-0 flex items-center justify-between">
          <span className="text-xs font-semibold text-muted-foreground uppercase">
            Course Fee
          </span>
          <span className="text-sm font-bold text-foreground">
            ₹{net.toLocaleString()}
          </span>
        </div>

        {/* Body */}
        <div className="overflow-y-auto p-6 flex-1">
          {step === 1 && (
            <StepPlanType
              planType={planType}
              setPlanType={setPlanType}
              onNext={() => setStep(2)}
            />
          )}
          {step === 2 && planType === "full_pay" && (
            <StepFullPay
              fullPayDate={fullPayDate}
              setFullPayDate={setFullPayDate}
              net={net}
              onBack={() => setStep(1)}
              onNext={() => setStep(3)}
            />
          )}
          {step === 2 && planType === "standard_emi" && (
            <StepStandardEMI
              config={standardConfig}
              setConfig={setStandardConfig}
              net={net}
              onBack={() => setStep(1)}
              onNext={() => setStep(3)}
            />
          )}
          {step === 2 && planType === "flexible" && (
            <StepFlexible
              firstInstallment={firstInstallment}
              setFirstInstallment={setFirstInstallment}
              net={net}
              onBack={() => setStep(1)}
              onNext={() => setStep(3)}
            />
          )}
          {step === 3 && (
            <StepReview
              net={net}
              planType={planType}
              installmentRows={buildInstallmentRows()}
              onBack={() => setStep(2)}
              onConfirm={handleConfirm}
              isSubmitting={isSubmitting}
            />
          )}
        </div>
      </div>
    </div>
  );
}
